
// This file was generated by the updater.
// TIMESTAMP: 2025-12-08 13:58:39
// A shared logic-only toggle used by both AIControls and TradingControls.
// NO styling here — styling is applied ONLY within each section.

import React, { useState } from "react";

export default function SharedAITradingToggle({ label = "Toggle", onChange }) {
    const [value, setValue] = useState(false);

    const toggle = () => {
        const newVal = !value;
        setValue(newVal);
        if (onChange) onChange(newVal);
    };

    return (
        <button onClick={toggle}>
            {label}: {value ? "ON" : "OFF"}
        </button>
    );
}
