// AUTO-GENERATED BY UPDATER — DO NOT MODIFY OUTSIDE UPDATES
/* TIMESTAMP */

import React from 'react';
import './Header.css';
import leftLogo from '../../assets/logo_left.png';
import rightLogo from '../../assets/logo_right.png';

export default function Header() {
  return (
    <div className="header-container fade-in">
      <div className="header-top">
        <img src={leftLogo} alt="left-logo" className="header-logo" />
        <h1 className="header-title">
          LIBERTY <span className="ai-glow">AI</span> TRADE
        </h1>
        <img src={rightLogo} alt="right-logo" className="header-logo" />
      </div>

      <h2 className="header-sub">
        AUTONOMOUS AI-DRIVEN CRYPTO TRADING DASHBOARD
      </h2>
    </div>
  );
}
